[terminal.shell]
program = "/bin/zsh"

[font]
size = 8.0

[font.normal]
family = "JetBrains Mono"

[font.italic]
family = "JetBrains Mono"
style = "italic"

[font.bold]
family = "JetBrains Mono"
style = "bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "bold italic"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.85 

[window.padding]
x = 4
y = 4

# Catppuccino theme scheme for Alacritty

[colors.primary]
background = '#1E1E2E'
foreground = '#D6D6D6'

[colors.cursor]
text = '#1E1E2E'
cursor = '#D9D9D9'

[colors.normal]
black = '#181A1F'
red = '#E86671'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#54AFBC'
white = '#ABB2BF'

[colors.bright]
black = '#5C6370'
red = '#E86671'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#54AFBC'
white = '#F7F7F7'

[colors.dim]
black = '#5C6370'
red = '#74423F'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#6E4962'
cyan = '#5C8482'
white = '#828282'

[scrolling]
history = 5000

[terminal]
