################
### MONITORS ###
################
# Laptop display (main)
monitor=eDP-1,preferred,auto,auto

# Mirror any additional displays to eDP-1
monitor=,preferred,auto,auto,mirror,eDP-1

# Vertical monitor on HDMI-A-1 (rotated 90 degrees)
#  monitor=HDMI-A-1,preferred,1920x0,auto,transform,1
# monitor=eDP-1,1920x1080,0x0,1
# monitor=HDMI-A-1,1920x1080,1920x0,1,transform,1


