##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# help with blurring issue
windowrule = noblur, floating:1
windowrule = noblur, class:^(Xdg-desktop-portal-gtk)$

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# -- Fix odd behaviors in IntelliJ IDEs --
#! Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrule = center,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
windowrule = nofocus,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
windowrule = noborder,class:^(jetbrains-.*)$,title:^(splash)$,floating:1

#! Center popups/find windows
windowrule = center,class:^(jetbrains-.*)$,title:^( )$,floating:1
windowrule = stayfocused,class:^(jetbrains-.*)$,title:^( )$,floating:1
windowrule = noborder,class:^(jetbrains-.*)$,title:^( )$,floating:1
#! Disable window flicker when autocomplete or tooltips appear
windowrule = nofocus,class:^(jetbrains-.*)$,title:^(win.*)$,floating:1

# file picker
windowrule = float,class:^(xdg-desktop-portal-gtk)$
windowrule = size 800 600,class:^(xdg-desktop-portal-gtk)$
windowrule = nomaxsize,class:^(xdg-desktop-portal-gtk)$

